name: Docker Image CI

on:
  push:
    branches: [ "feat/initial-architecture-and-documentation-5776513129489242216" ]
  pull_request:
    branches: [ "feat/initial-architecture-and-documentation-5776513129489242216" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
